### ISSUE TITLE
Request the CIFAR10 dataset

### ISSUE THREAD

**Issue by ye-zero** [chakkritte/EEEA-Net#1]
Hello, there are too many annotated versions of the CIFAR10 dataset online. Can you share the CIFAR10 dataset link that you used?   Thanks a lot.

**Comment by chakkritte** [comment]
Hi @ye-zero,

https://github.com/chakkritte/EEEA-Net/blob/main/EEEA/cifar/eeea/data/datasets.py#L83

My code used torchvision.datasets to automatically download the CIFAR10 dataset.
