### ISSUE TITLE
Error while running the code

### ISSUE THREAD

**Issue by Junaid199f** [chakkritte/EEEA-Net#2]
Hi! I am running your code but it giving this error:

RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

Could you please help me how to fix it

**Comment by chakkritte** [comment]
Hi @Junaid199f,

I reckon your PyTorch version may mismatch with my code; which version of PyTorch and TorchVision are you using? 

I recommend using PyTorch **1.6** and TorchVision **0.7.0**.
